import {
  Activity,
  Beer,
  Briefcase,
  Calculator,
  Camera,
  Car,
  Code,
  Coffee,
  Croissant,
  Droplet,
  Dumbbell,
  Flower2,
  GraduationCap,
  Hammer,
  Hand,
  HeartPulse,
  Home,
  KeyRound,
  Languages,
  Leaf,
  Megaphone,
  PaintbrushVertical,
  PawPrint,
  Pill,
  Plane,
  Scale,
  Scissors,
  ShieldCheck,
  Sparkles,
  Stethoscope,
  Truck,
  UtensilsCrossed,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  megaphone: Megaphone,
  scale: Scale,
  stethoscope: Stethoscope,
  utensils: UtensilsCrossed,
  hammer: Hammer,
  code: Code,
  home: Home,
  scissors: Scissors,
  "graduation-cap": GraduationCap,
  car: Car,
  dumbbell: Dumbbell,
  camera: Camera,
  coffee: Coffee,
  beer: Beer,
  croissant: Croissant,
  calculator: Calculator,
  shield: ShieldCheck,
  sparkles: Sparkles,
  hand: Hand,
  flower: Flower2,
  activity: Activity,
  paw: PawPrint,
  pill: Pill,
  "heart-pulse": HeartPulse,
  zap: Zap,
  droplet: Droplet,
  paintbrush: PaintbrushVertical,
  key: KeyRound,
  truck: Truck,
  languages: Languages,
  leaf: Leaf,
  plane: Plane,
};

export function CategoryIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = ICONS[name] ?? Briefcase;
  return <Icon className={className} />;
}
