import {
  Accessibility,
  Activity,
  Baby,
  BedDouble,
  Beer,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Bug,
  Calculator,
  Camera,
  Car,
  Code,
  Coffee,
  Croissant,
  Droplet,
  Dumbbell,
  Flower2,
  Footprints,
  Fuel,
  Gem,
  Glasses,
  GraduationCap,
  Hammer,
  Hand,
  HeartPulse,
  Home,
  IceCreamCone,
  KeyRound,
  Languages,
  Leaf,
  Megaphone,
  Music,
  Package,
  PaintbrushVertical,
  PartyPopper,
  PawPrint,
  Pill,
  Plane,
  Printer,
  Ruler,
  Salad,
  Scale,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  SprayCan,
  Stamp,
  Stethoscope,
  Sun,
  Syringe,
  TreePine,
  Truck,
  Users,
  UtensilsCrossed,
  Waves,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  megaphone: Megaphone,
  scale: Scale,
  stethoscope: Stethoscope,
  utensils: UtensilsCrossed,
  hammer: Hammer,
  code: Code,
  home: Home,
  scissors: Scissors,
  "graduation-cap": GraduationCap,
  car: Car,
  dumbbell: Dumbbell,
  camera: Camera,
  coffee: Coffee,
  beer: Beer,
  croissant: Croissant,
  calculator: Calculator,
  shield: ShieldCheck,
  sparkles: Sparkles,
  hand: Hand,
  flower: Flower2,
  activity: Activity,
  paw: PawPrint,
  pill: Pill,
  "heart-pulse": HeartPulse,
  zap: Zap,
  droplet: Droplet,
  paintbrush: PaintbrushVertical,
  key: KeyRound,
  truck: Truck,
  languages: Languages,
  leaf: Leaf,
  plane: Plane,
  shirt: Shirt,
  footprints: Footprints,
  gem: Gem,
  glasses: Glasses,
  book: BookOpen,
  sofa: Sofa,
  smartphone: Smartphone,
  wrench: Wrench,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  bike: Bike,
  "ice-cream": IceCreamCone,
  bed: BedDouble,
  party: PartyPopper,
  music: Music,
  brain: Brain,
  salad: Salad,
  syringe: Syringe,
  ruler: Ruler,
  stamp: Stamp,
  briefcase: Briefcase,
  printer: Printer,
  users: Users,
  sun: Sun,
  fuel: Fuel,
  baby: Baby,
  waves: Waves,
  bug: Bug,
  "spray-can": SprayCan,
  package: Package,
  trees: TreePine,
  accessibility: Accessibility,
};

export function CategoryIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = ICONS[name] ?? Briefcase;
  return <Icon className={className} />;
}
